### PR TITLE
Graphgrammar clean

### PR DESCRIPTION
**Pull request by Podsiadlo**
Hi!
I have updated the project to be able to create obtuse triangles (option -square) and I have worked on things you've mentioned before. (It took me too much time. I'm sorry, the coronavirus situation caused a lot of problems.) Also, I have written option to write output into .node,.ele... files. The standard one is AVS UCD (.inp). 
To run this you need terrain data from https://dds.cr.usgs.gov/srtm/version2_1/SRTM3/. I have uploaded them temporally on my website: http://podsiadl.pl/srtm/SRTM3.zip (all the files are in single directory there).
I do not know how big area you want to have, but as the Earth is not flat I am using conversion to [UTM](https://en.wikipedia.org/wiki/UTM) coordinates system and because of this the maximal area is single UTM zone.
Sample set of arguments: ./longestedge -l 25 -s 14 -N 52.4 -S 49. -E 23.1 -W 18.1 -data dataDirectory -o outputFile -square -altOutput

### CODE REVIEW

**Review by insertinterestingnamehere — APPROVED** [review]
Looks great! Thank you! We recently did some reorganizing in the main Galois repo so I'm updating this to match those changes.

**Comment by bozhiyou** [comment]
@Podsiadlo Thanks a lot! Is it able to generate non-obtuse triangles under some specific case so far? Sorry I'm currently not familiar with the source code.

**Comment by insertinterestingnamehere** [comment]
I think we'll need to check that condition ourselves. Hopefully the mesh generator will, at least in some cases, give us a mesh where that's already true though.

**Comment by bozhiyou** [comment]
@Podsiadlo The output seems problematic. With exactly the sample that you gave `./longestedge -l 25 -s 14 -N 52.4 -S 49. -E 23.1 -W 18.1 -data dataDirectory -o outputFile -square -altOutput`, the second endpoint of segment 128, 130, 131, etc. is invalid, which exceeds the total number of nodes. Could you please have a look at this?

**Pull request merged**
